# WARN[0000] /Users/anhnn/Documents/learning/fptu/semester8Sprint26/dsp/projects/dsp391m-traffic-law-chatbot/chatbot/docker-compose.yml: 
# the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
# version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: traffic_law_postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
    # mount to ../postgres_data on host machine
      - ../data/postgres_data:/var/lib/postgresql/data
    networks:
      - traffic_net

networks:
  traffic_net:
    driver: bridge
